es:
  image: elasticsearch
web:
  image: prakhar1989/foodtrucks-web
  command: python app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/code
  links:
    - es
web2:
  image: prakhar1989/foodtrucks-web
  command: python app.py
  ports:
    - "5001:5000"
  volumes:
    - .:/code
  links:
    - es
